$(document).ready(function(){
    $(".visual").bxSlider({
        controls:false,
        pager:false
    });
    $(".sponserWrap").bxSlider({
        controls:false,
        pager:false
    });
    $(".mainLi").mouseover(function(){
        $(".subMenu").stop().slideDown();
    });
    $(".mainLi").mouseout(function(){
        $(".subMenu").stop().slideUp();
    })
});